name: PdfChest
description: A new Flutter project.

publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^0.12.2
  dio: ^3.0.10
  ext_storage: ^1.0.3
  permission_handler: ^6.0.1+1
  share: ^0.6.5+4
  rate_my_app: ^0.7.2
  url_launcher: ^6.0.2
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter_launcher_name:
  name: "Pdf Chest"